#!/bin/sh

export GOPRIVATE=github.com
export GOPROXY=https://goproxy.cn,direct
export ctx_dev=http://localhost:9020

ISH_CONF_WORK=~/usr/local/work
if [ -f ~/.ish/plug.sh ] && source ~/.ish/plug.sh; then
    require conf.sh
fi

[ -f etc/local.sh ] && source etc/local.sh
export PATH=$PWD/bin:$PATH
