#!/bin/sh

export GOPATH=~/bin/go
export GOROOT=~/usr/local/go
export GOPRIVATE=git.zuoyebang.cc,github.com

ISH_CONF_WORK=~/usr/local/work
if [ -f ~/.ish/plug.sh ] && source ~/.ish/plug.sh; then
    require conf.sh

    ish_ctx_cli_prompt
fi

