#!/bin/sh

if [ -f ~/.ish/plug.sh ]; then
   source ~/.ish/plug.sh

   require github.com/shylinux/shell help.sh
   require github.com/shylinux/shell base/base.sh
   require github.com/shylinux/shell core/core.sh
   require github.com/shylinux/shell misc/misc.sh
fi

