#!/bin/sh

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(tmux git)

source $ZSH/oh-my-zsh.sh
source ~/.oh-my-zsh/plugins/z/z.sh

export PROMPT=$LOCAL_PROMPT'%![%*]%c$ '
export EDITOR=vim

bindkey -e
bindkey jk accept-line
bindkey "^N" down-line-or-beginning-search
bindkey "^P" up-line-or-beginning-search
bindkey -M vicmd j down-line-or-beginning-search
bindkey -M vicmd k up-line-or-beginning-search

export GOPRIVATE=github.com
export GOPROXY=https://goproxy.cn,direct
export ctx_dev=http://localhost:9020

ISH_CONF_WORK=~/usr/local/work
if [ -f ~/.ish/plug.sh ] && source ~/.ish/plug.sh; then
    require conf.sh
fi

[ -f etc/local.sh ] && source etc/local.sh
# export PATH=$PWD/bin:$PWD/usr/local/go/bin:$PATH
