#!/bin/sh

if [ -f ~/.ish/plug.sh ] && source ~/.ish/plug.sh; then
    require conf.sh

    ish_ctx_cli_prompt
fi

export ZSH=$HOME/.oh-my-zsh
# ZSH_THEME="robbyrussell"
plugins=(tmux git)

source $ZSH/oh-my-zsh.sh

export EDITOR=vim

bindkey "^N" down-line-or-beginning-search
bindkey "^P" up-line-or-beginning-search

